# Site settings
title: Freifunk Kassel
tagline: Das freie Bürgernetz in Kassel
author:
  name: Freifunk Kassel
  email: hallo@freifunk-kassel.de
  github: freifunkks
  twitter: freifunkks

permalink: /news/:title/

nav_pages:
  - id: info
    title: Info
    url: /info/
  - id: news
    title: News
    url: /news/
  - id: firmware
    title: Firmware
    url: /firmware/
  - id: map
    title: Karte
    url: /map/
  - id: about
    title: Über FFKS
    url: /about/

# Build settings
exclude: ["CNAME"]
highlighter: pygments
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
